Update Dockerfile and clean up README instructions
Commented out the HEALTHCHECK and user creation steps in the Dockerfile for easier debugging or development. Improved README formatting, added a project title, switched code blocks to use bash syntax, and removed redundant sections for clarity. Minor whitespace adjustment in animated.css.

diff --git a/Docker/Dockerfile b/Docker/Dockerfile
--- a/Docker/Dockerfile
+++ b/Docker/Dockerfile
@@ -2,7 +2,7 @@ FROM apache/airflow:3.1.0
 COPY requirements.txt /
 RUN pip install --no-cache-dir -r /requirements.txt
 
-HEALTHCHECK CMD curl --fail http://localhost:8080/health || exit 1
+# HEALTHCHECK CMD curl --fail http://localhost:8080/health || exit 1
 
-RUN useradd -m airflowuser
-USER airflowuser
+# RUN useradd -m airflowuser
+# USER airflowuser
